// Code generated by ghp. DO NOT EDIT.
package main

import (
	"log"
	"net/http"
	"os"

	gen "ghp/.ghp/gen"
	ghp "ghp/runtime"
)

func main() {
	addr := os.Getenv("GHP_ADDR")
	if addr == "" {
		addr = ":8080"
	}
	mux := http.NewServeMux()
	gen.Register(mux)
	log.Fatal(ghp.Serve(addr, mux))
}
